# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-SpamAssassin
version:      3.003002
version_from: lib/Mail/SpamAssassin.pm
installdirs:  site
requires:
    Archive::Tar:                  1.23
    Digest::SHA1:                  0
    Errno:                         0
    File::Copy:                    2.02
    File::Spec:                    0.8
    HTML::Parser:                  3.43
    IO::Zlib:                      1.04
    Mail::DKIM:                    0.31
    Net::DNS:                      0.34
    NetAddr::IP:                   4
    Pod::Usage:                    1.1
    Sys::Hostname:                 0
    Time::HiRes:                   0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
